import Head from "next/head"
import { HTMLAttributes } from "react"
import Loading from "../components/loading"

type Props = HTMLAttributes<any> & {
    children: any
    titlePage: string
    isLoading?: boolean
    messageLoading?: string
}

export default function Default({ children, titlePage, isLoading = false, messageLoading = '', ...rest }: Props) {
    const title = titlePage ? titlePage : 'Next App'
    return (
        <div {...rest}>
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {isLoading ? <Loading message={messageLoading} /> : children}
        </div>
    )
}